### PR TITLE
(fix) Fix typing for multiple tagged templates functions (Fixes #91)

### LINKED ISSUE #91: Typescript - Expected X arguments, but got Y
Hi there! Awesome work with this library.

I'm using `preact-custom-element` with TypeScript,  and it's throwing an error since when trying to use props inside a `styled` more than once

image

I'm getting: 

```
Expected 1-2 arguments, but got 3.ts(2554)
```
The examples don't seem to have to specify this, so is this something with my code or the library?

Here are my relevant dependencies:
```
 "goober": "^1.6.3",
 "preact": "^10.2.1",
"typescript": "^3.7.5"
```

### PR DESCRIPTION
**Pull request by cristianbote**
This one fixes the typings for multiple functions inside the tagged template. (#91)

### CODE REVIEW

File: goober.d.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ declare namespace goober {
     type StyledVNode<T> = (props: T, ...args: any[]) => any;
     type Tagged<T> = (
         tag: CSSAttribute | TemplateStringsArray,
-        props?: (props: T) => CSSAttribute | string | number | undefined
+        ...props: Array<(props: T) => CSSAttribute | string | number | undefined>
```
Comment (cristianbote) [inline goober.d.ts]: It works @krisboit thanks for the suggestion! 😉
