### PR TITLE
[FIX] base64 url in string is now working

### LINKED ISSUE #173: background image with base64 image url not working
Hi, background image with base64 data image is not working a expected
It can be easily reproduced by
```
import { css } from "goober";

const HeaderClass = css`
  color: white;
  padding: 1em;
  background-image: url("data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7");
`;

document.getElementById("app").innerHTML = `
<h1 class="${HeaderClass}">Hello Vanilla!</h1>
<div>
  We use Parcel to bundle this sandbox, you can find more info about Parcel
  <a href="https://parceljs.org" target="_blank" rel="noopener noreferrer">here</a>.
</div>
`;

```

### PR DESCRIPTION
**Pull request by ksenginew**
Fixes #173 
Also you can add a tick to #207 
You can write css without last semicolon. But goober wasn't supported. It's now working on goober.
eg:-
```diff
h1 {
  color: red;
-  opacity: 1;
+  opacity: 1
}
```
The regular expression is long but works finely. Inspired by 

https://github.com/reworkcss/css/blob/434aa1733f275a67ea700311451b98a14f8cc21a/lib/parse/index.js#L227

_Sadly_
**Size Change:** +105 B (2%) 

**Total Size:** 4.92 kB

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/goober.esm.js` | 1.21 kB | +25 B (2%) |  |
| `dist/goober.js` | 1.21 kB | +27 B (2%) |  |
| `dist/goober.modern.js` | 1.21 kB | +25 B (2%) |  |
| `dist/goober.umd.js` | 1.28 kB | +28 B (2%) |  |

<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

### CODE REVIEW

**Comment by ksenginew** [comment]
@cristianbote 
I am sorry for this crazy regular expression. But it works. _maybe we can reduce the size._

**Size Change:** +129 B (2%) 

**Total Size:** 4.95 kB

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/goober.esm.js` | 1.22 kB | +31 B (2%) |  |
| `dist/goober.js` | 1.22 kB | +33 B (2%) |  |
| `dist/goober.modern.js` | 1.22 kB | +31 B (2%) |  |
| `dist/goober.umd.js` | 1.29 kB | +34 B (2%) |  |


<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Comment by cristianbote** [comment]
Yeah the regex is complex now. 😬 I think I went through it a couple of times to get it and still haven't figured it out. Yet! I'll keep you posted. Another avenue with the regex is to handle the bg image differently.

**Comment by ksenginew** [comment]
Hi @cristianbote I can explain the regex. Can we discuss to reduce the size of regex.

File: src/core/astish.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-let newRule = /(?:([\u0080-\uFFFF\w-%@]+) *:? *([^{;]+?);|([^;}{]*?) *{)|(}\s*)/g;
+let newRule = /(?:([\u0080-\uFFFF\w-%@]+) *:? *((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^{};])+)(?=[;}])|([^;}{]*?) *{)|(}\s*)/g;
```
Comment (cristianbote) [inline src/core/astish.js:1]:
```suggestion
let newRule = /(?:([\u0080-\uFFFF\w-%@]+) *:? *((?:\([^\)]+?\)|[^{};])+)(?=[;}])|([^;}{]*?) *{)|(}\s*)/g;
```

Thanks for the ping! So deep diving into the rule was wondering why the need to target the `'|"` chars? 🤔 so did a quick test, remove them and tests are passing. So was there any particular caveat that you were chasing here?

Comment (ksenginew) [reply src/core/astish.js:1]: Oh, I'll explain the RegEx. Also you can inspect this regex via https://regex101.com/r/MAfztK/1 link. It's pretty good.

Comment (cristianbote) [reply src/core/astish.js:1]: With the above the changes are only `+16B` which is not bad at all.

Comment (cristianbote) [reply src/core/astish.js:1]: @ksenginew yeah saw the regex101 explanation. Here's the regex101 example with the trimmed down rule https://regex101.com/r/3ylRk5/1

Comment (cristianbote) [reply src/core/astish.js:1]: The initial regex rule matches the `'|"` and also the `(|)` braces. So that was my question if there's another case where this leads to issues if we remove the matching for `'|"`?

Comment (ksenginew) [reply src/core/astish.js:1]: @cristianbote your regex fails for `content` property.
```css
.close-me::after {
    content: "closing with ; now it's closed"; /* failed here */
}
```

**My solution will not fail in rare cases. But your solution looks enough.**

This is our OLD regular expression.
```py
/(?:([\u0080-\uFFFF\w-%@]+) *:? *([^{;]+?);|([^;}{]*?) *{)|(}\s*)/g
```
We can split it -`.split("|")`
- declaration
    ```py
   (?:([\u0080-\uFFFF\w-%@]+) *:? *([^{;]+?);
    ```
- selector or at rule
    ```py
    ([^;}{]*?) *{)
    ```
- last `}` character
    ```py
    (}\s*)
    ```

We want to change the part of declaration
```py
(?:([\u0080-\uFFFF\w-%@]+) *:? *([^{;]+?);
```
- property
    ```
    (?:([\u0080-\uFFFF\w-%@]+)
    ```
- `:` mark. It's optional to handle `@charset`
    ```css
     *:? *
    ```
- value
    ```py
   ([^{;]+?);
   ```

We should choose value 
```py
 ([^{;]+?);
```

I had changed it to
```diff
- ([^{;]                                             +?   );
+ ((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^{};])+)(?=[;}])
```
inside this group
```py
((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^{};])+)
```
There are 3 uncaptured groups added.
```py
'(?:\\'|.)*?'
```
```py
"(?:\\"|.)*?"
```
```py
\([^\)]*?\
```
```py
[^{};])  # already existed
```
These 3 uncp... groups handles double quoted strings, single quoted strings and CSS function calls.
```py
'(?:\\'|.)*?'
```

Can we take a last decision. then I can optimize regex and commit it.

Comment (cristianbote) [reply src/core/astish.js:1]: Oh, that makes sense now, those are for the `content` property which can have a variation of things inside it and not mention defined differently based on the input format.

Ok let's merge this and we can look for things to minify later on. Great work @ksenginew!
